name: kpi_analytics
version: '1.0'
config-version: 2

profile: default

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Optional but recommended
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kpi_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
